# tlp parameter file
  car_width: 0.3
  wheelbase: 0.3
  obstacle_avoidance: true
  min_distance: 0.8
  steering_angle_parameter: 0.6
  laser_max_dist: 2
  use_base_link_frame: true
  min_object_size: 5
