MAX_DIST: 0.56
MIN_DIST: 0.55

NUM_MEAN_SAMPLES: 10

MAX_GAP_DEPTH: 0.35
MIN_GAP_DEPTH: 0.15

MIN_GAP_LENGTH: 0.5
MAX_GAP_LENGTH: 1.0

RANGE_THRESHOLD: 0.05

BACKWARD_THRESHOLD_1: 0.30
BACKWARD_THRESHOLD_2: 0.15

LINEAR_SPEED: 0.45
ANGULAR_SPEED: 0.2
