MAX_DIST: 0.40
MIN_DIST: 0.30
NUM_MEAN_SAMPLES: 10

MAX_GAP_DEPTH: 0.40
MIN_GAP_DEPTH: 0.30

MIN_GAP_LENGTH: 0.5
MAX_GAP_LENGTH: 1.0

RANGE_THRESHOLD: 0.05

BACKWARD_THRESHOLD_1: 0.2
BACKWARD_THRESHOLD_2: 0.1

LINEAR_SPEED: 0.3
