set(_CATKIN_CURRENT_PACKAGE "tas_local_planner")
set(tas_local_planner_MAINTAINER "sebastian <sebastian@todo.todo>")
set(tas_local_planner_DEPRECATED "")
set(tas_local_planner_VERSION "0.0.0")
set(tas_local_planner_BUILD_DEPENDS "roscpp" "std_msgs" "nav_core")
set(tas_local_planner_RUN_DEPENDS "nav_core" "roscpp" "std_msgs")
set(tas_local_planner_BUILDTOOL_DEPENDS "catkin")